---
# tasks file for mmv.clicomfort

# NOTE: role mmv-ru.vim included by dependency

- name: CLI tools for comfort and debug
  package:
    name:
    - bash-completion
    - yum-utils
    - tcpdump
    - bind-utils # host nslookup dig
    state: present
  tags: [comfort, debug, packages]

- name: CLI tools for comfort and debug
  package:
    name:
    - mlocate
    state: present
  notify: update mlocate DB
  tags: [comfort, debug, packages]

- name: selinux CLI tools for comfort and debug
  package:
    name:
    - setroubleshoot-server
    - setroubleshoot
    state: present
  when: ansible_selinux.status != "disabled" and
        ansible_selinux.config_mode == "enforcing"
  tags: [comfort, debug, packages, selinux]

- name: Disable Ctrl-S Ctrl-Q (software flow control in terminal)
  copy:
    content: |
      # Disable Ctrel-S Ctrl-Q software flow control:
      stty -ixon
    dest: /etc/profile.d/flowcontrol.sh
  tags: [comfort, configure]
