---
# tasks file for mmv.clicomfort

# NOTE: role mmv-ru.vim included by dependency

- name: CLI tools for comfort and debug
  package:
    name:
    - bash-completion
    - yum-utils
    - mlocate
    - tcpdump
    - setroubleshoot-server
    - setroubleshoot
    - bind-utils # host nslookup dig
    state: present
  tags: [comfort, debug, packages]

- name: update mlocate DB
  command: updatedb
  args:
    creates: /var/lib/mlocate/mlocate.db
  tags: [comfort]
